FILES = Buffer.java Coordinator.java Consumer.java Producer.java
PKG = Makefile README.txt
TAR_NAME = Andy-Donis_Paz-HW5.tar

build:
	javac -g $(FILES)
package:
	tar cvzf $(TAR_NAME) $(FILES) $(PKG)
clean:
	rm -f $(OUT_EXE)